# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: befb337f6083dc7811845298bd9397f115dd19ec349b1d86892e7fb2e5c35d4382bdab66d8dba0a7d562a07b4c60251e9c94e40f7ced127b758b1331c6357b94

test:
  secret_key_base: c5f796958c75c95f520ad62519e368b97905ebc1d710015ea53fc64f6a831946796345c5b30f98da3272801f6e0b852adb556af1e83c364eab2aedbd9da0fd66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
